### ISSUE TITLE
NA-Plan

### ISSUE THREAD

**Issue by pope410211** [pope410211/TIY-Assignments#30]
##### PART 1
- _Write HTML_
  - [x] Create a list view of items
    - using `<ul>` & `<li>`
    - [x] Nested according to source material
  - [x] Listception!
  - Use Lorem Ipsum
##### PART 2
- _Write SASS_
  - Create basic styling
  - [x] font color(s)
  - [x] spacing
  - [x] icons 
  - [x] Hide elements
##### PART 3
- _JAVASCRIPT_
  - [x] Create a JS file that can toggle hidden elements

---

[Nested Accordion Source Mat.](http://tympanus.net/Blueprints/NestedAccordion/)

**Comment by pope410211** [comment]
![na-basic-view](https://cloud.githubusercontent.com/assets/12172658/8855044/0a29fc54-3131-11e5-874e-d5fc1d3fd7c0.png)  

---

![na-accordion-view](https://cloud.githubusercontent.com/assets/12172658/8855045/0a2a6810-3131-11e5-9e48-fdddc502979f.png)

**Comment by pope410211** [comment]
https://github.com/pope410211/TIY-Assignments/pull/31
